module.exports.config = {
  name: "girldp",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Aasif Alam",
  description: "Random 6-pack photos",
  commandCategory: "Random-IMG",
  usages: "dpg",
  cooldowns: 1,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
    var link = [
"https://i.imgur.com/gx96pt9.jpeg",
"https://i.imgur.com/Yq2dNvD.jpeg",
"https://i.imgur.com/204H9no.jpeg",
"https://i.imgur.com/bmKahkk.jpeg",
"https://i.imgur.com/d9Z4e5N.jpeg",
"https://i.imgur.com/Vtu7pVo.jpeg",
"https://i.imgur.com/p5Jvjjj.jpeg",
"https://i.imgur.com/7e8xUI2.jpeg",
"https://i.imgur.com/ejPSHRi.jpeg",
"https://i.imgur.com/ompIx4W.jpeg",
"https://i.imgur.com/VFoNkte.jpeg",
"https://i.imgur.com/uwszp6r.jpeg",
"https://i.imgur.com/qZWig6p.jpeg",
"https://i.imgur.com/Dw1D2Ji.jpeg",
"https://i.imgur.com/fYJrOY5.jpeg",
"https://i.imgur.com/o5myzQ8.jpeg",
"https://i.imgur.com/DGk60tJ.jpeg",
"https://i.imgur.com/vmawGZc.jpeg",
"https://i.imgur.com/r9Bo2Qn.jpeg",
"https://i.imgur.com/iOBx0Qg.jpeg",
"https://i.imgur.com/xV58bdv.jpeg",
"https://i.imgur.com/fHUlyEB.jpeg",
"https://i.imgur.com/Yd4aQo4.jpeg",
"https://i.imgur.com/6HB72QA.jpeg",
"https://i.imgur.com/i3C2XCz.jpeg",
"https://i.imgur.com/8UIu17f.jpeg",
"https://i.imgur.com/baIlvEg.jpeg",
"https://i.imgur.com/HYLjwxj.jpeg",
"https://i.imgur.com/4PtQ24J.jpeg",
"https://i.imgur.com/yCIGTs8.jpeg",
"https://i.imgur.com/nEQDVij.jpeg",
"https://i.imgur.com/IuQydQC.jpeg",
"https://i.imgur.com/2YbMuHD.jpeg",
"https://i.imgur.com/HrJUijs.jpeg",
"https://i.imgur.com/EWXZJ8j.jpeg",
"https://i.imgur.com/Cxbv5Qv.jpeg",
"https://i.imgur.com/mdZl6YA.jpeg",
"https://i.imgur.com/KgS2dXP.jpeg",
"https://i.imgur.com/fSK8GbF.jpeg",
"https://i.imgur.com/rKHoovj.jpeg",
"https://i.imgur.com/DDN2FqE.jpeg",
"https://i.imgur.com/8SnuMmH.jpeg",
"https://i.imgur.com/9rI7WM9.jpeg",
"https://i.imgur.com/GY3obl2.jpeg",
"https://i.imgur.com/R5aamUt.jpeg",
"https://i.imgur.com/EsTcNLF.jpeg",
"https://i.imgur.com/srUx9TF.jpeg",
"https://i.imgur.com/6VgsDuW.jpeg",
"https://i.imgur.com/8grFh7K.jpeg",
"https://i.imgur.com/L529nyo.jpeg",
"https://i.imgur.com/4wGgw4c.jpeg",
"https://i.imgur.com/ZJ2ogWB.jpeg",
"https://i.imgur.com/8x1xp5m.jpeg",
"https://i.imgur.com/gvlx61F.jpeg",
"https://i.imgur.com/3GQpmdm.jpeg",
"https://i.imgur.com/n7094fM.jpeg",
"https://i.imgur.com/NCRxft1.jpeg",
"https://i.imgur.com/APKeEDx.jpeg",
"https://i.imgur.com/4p5IUJ8.jpeg",
"https://i.imgur.com/8XqAylA.jpeg",
"https://i.imgur.com/jcHHovk.jpeg",
"https://i.imgur.com/cCspFwy.jpeg",
"https://i.imgur.com/MmXGShA.jpeg",
"https://i.imgur.com/k7ASVnP.jpeg",
"https://i.imgur.com/ONZ12Oi.jpeg",
"https://i.imgur.com/06gKphw.jpeg",
"https://i.imgur.com/EDef2sL.jpeg",
"https://i.imgur.com/pxmjXyu.jpeg",
"https://i.imgur.com/adG13Pm.jpeg",
"https://i.imgur.com/Mg1LfrK.jpeg",
"https://i.imgur.com/V6IdXAQ.jpeg",
"https://i.imgur.com/MrKzxdp.jpeg",
"https://i.imgur.com/me569i7.jpeg",
"https://i.imgur.com/oBQmJfx.jpeg",
"https://i.imgur.com/YY2tI2o.jpeg",
"https://i.imgur.com/zRFhSh5.jpeg",
"https://i.imgur.com/z8H4zJM.jpeg",
"https://i.imgur.com/RhoXude.jpeg",
"https://i.imgur.com/9eOOn1q.jpeg",
"https://i.imgur.com/ExaoJEm.jpeg",
"https://i.imgur.com/oyD5xhG.jpeg",
"https://i.imgur.com/clZqg6g.jpeg",   
"https://i.imgur.com/u10v85f.jpeg",
"https://i.imgur.com/2PbfFq2.jpeg",
"https://i.imgur.com/3Fryq9U.jpeg",
"https://i.imgur.com/csO9tVL.jpeg",
"https://i.imgur.com/V4RMkNp.jpeg",
"https://i.imgur.com/yLW06aw.jpeg",
"https://i.imgur.com/ftk87yw.jpeg",
"https://i.imgur.com/kw3Ugkn.jpeg",
"https://i.imgur.com/FSywaVM.jpeg",
"https://i.imgur.com/txNC0bc.jpeg",
"https://i.imgur.com/rFOxKmL.jpeg",
"https://i.imgur.com/K5vpi8x.jpeg",
"https://i.imgur.com/prAb2q1.jpeg",
"https://i.imgur.com/gz2OoBl.jpeg",
"https://i.imgur.com/gGNFFDG.jpeg",
"https://i.imgur.com/ETWDuhb.jpeg",
"https://i.imgur.com/7Hs2CqS.jpeg",
"https://i.imgur.com/cIXeW5Z.jpeg",
"https://i.imgur.com/jpvTnE1.jpeg",
"https://i.imgur.com/lzu8buC.jpeg",
"https://i.imgur.com/jN2bLjm.jpeg",
"https://i.imgur.com/ZKCw0nW.jpeg",
"https://i.imgur.com/wJY4amH.jpeg",
"https://i.imgur.com/EXzugE4.jpeg",
"https://i.imgur.com/xqL3Eo7.jpeg",
"https://i.imgur.com/8L0JWNC.jpeg",
"https://i.imgur.com/LWw6psU.jpeg",
"https://i.imgur.com/uUSGu5Q.jpeg",
"https://i.imgur.com/jVsrOoP.jpeg",
"https://i.imgur.com/A1sFSyn.jpeg",
"https://i.imgur.com/wLnIP9L.jpeg",
"https://i.imgur.com/1ughzXO.jpeg",
"https://i.imgur.com/3AoKZst.jpeg",
"https://i.imgur.com/1qVSOUX.jpeg",
"https://i.imgur.com/AlFpTBj.jpeg",
"https://i.imgur.com/5KaN2WZ.jpeg",
"https://i.imgur.com/gpUNyqI.jpeg",
"https://i.imgur.com/2eFNr8d.jpeg",
"https://i.imgur.com/zH8tKmP.jpeg",      
"https://i.imgur.com/aaV4WVsq.jpg"
     ];
     var callback = () => api.sendMessage({body:`✨️👸✨️`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"));  
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
   };
